- id: d_SE2_car_v-cam360
  desc: A simple car with an omnidirectional camera.
  dynamics: d_SE2_car_v
  sensors:
      - type: cam360
        pose: [0,0,0]
  body:
      - type: sphere0.2
        pose: [0,0,0]


- id: d_SE2_rb_v-rf360
  desc: An omnidirectional robot with a 360deg range finder.
  dynamics: d_SE2_rb_v
  sensors:
      - type: rf360
        pose: [0,0,0]
  body:
      - type: sphere0.2
        pose: [0,0,0]
