- id: landroid-hokuyo
  desc: "Model for the landroid; only Hokuyo."
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: rf_f270_n180
        pose: [0.03,0,0]
        extra:
          skin: landroid-rf
        
  radius: 0.2
  extra:
    skin: landroid
  
- id: landroid-hokuyo-4cam
  desc: "Model for the landroid; Hokuyo + cams"
  id_dynamics: d_SE2_car_v
  sensors:
    - id_sensor: rf_f270_n180
      pose: [0.03,0,0]
      extra:
          skin: landroid-rf
    - id_sensor: cam_f60_n45
      pose: [0.1,0,0]
      extra:
          skin: landroid-cam
    - id_sensor: cam_f60_n45
      pose: [-0.03,0.05,+90]
      extra:
          skin: landroid-cam
    - id_sensor: cam_f60_n45
      pose: [-0.03,-0.05,-90]
      extra:
          skin: landroid-cam
    - id_sensor: cam_f60_n45
      pose: [-0.1,0,180]
      extra:
          skin: landroid-cam
  radius: 0.2
  extra:
    skin: landroid

  
- id: landroid-4cam
  desc: "Model for the landroid; only cam"
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: cam_f60_n45
        pose: [0.1,0,0]
        extra:
            skin: landroid-cam
      - id_sensor: cam_f60_n45
        pose: [-0.03,0.05,+90]
        extra:
            skin: landroid-cam
      - id_sensor: cam_f60_n45
        pose: [-0.03,-0.05,-90]
        extra:
            skin: landroid-cam
      - id_sensor: cam_f60_n45
        pose: [-0.1,0,180]
        extra:
            skin: landroid-cam
  radius: 0.2
  extra:
    skin: landroid
