

class VehiclesConstants:
    TEST_ADDITIONAL_CONFIG_DIR_ENV = 'VEHICLES_TEST_CONFIG'
    DEFAULT_SIMULATION_DT = 0.1

    SENSOR_TYPE_RANGEFINDER = 'Rangefinder'
    SENSOR_TYPE_FIELDSAMPLER = 'FieldSampler'
    SENSOR_TYPE_PHOTORECEPTORS = 'Photoreceptors'

    PRIMITIVE_SOURCE = 'Source'
    PRIMITIVE_CIRCLE = 'Circle'
    PRIMITIVE_POLYLINE = 'PolyLine'
