# This file describes the available sensors
- id: sphere0.2
  desc: A collision sensor
  code: 
      - simple_vehicles.sensors.SphereCollision
      - radius: 0.2

- id: cam360
  desc: An omnidirectional camera
  code: 
      - simple_vehicles.sensors.Camera
      - num_sensels: 180
        fov_deg:     360
        smooth_deg:  4
        tau:         0.1

- id: cam180
  desc: A camera with 180fov.
  code: 
      - simple_vehicles.sensors.Camera
      - num_sensels: 180
        fov_deg:     180
        smooth_deg:  4
        tau:         0.1
          
