# Define constants
# OK, now we start
- MAX_LINEAR_VEL: &MAX_LINEAR_VEL 1  # max linear velocity
  MA: &MA 1  # max angular velocity
  MF: &MF 2  # max force
  MASS: &MASS 1  # robot mass  
  CAR_LENGTH: &CAR_LENGTH 0.5
  AXIS_DIST: &AXIS_DIST 0.7
  DAMPING: &DAMPING 1
  MAX_STEERING_ANGLE: &MAX_STEERING_ANGLE 0.52359877 # 30deg
  id:   d_R1_rb_v
  desc: 'Rigid body on R1, controlled in velocity.'
  code: 
  - vehicles.library.dynamics.EuclideanVel
  - ndim: 1
    max_velocity: [*MAX_LINEAR_VEL]

- id:   d_R2_rb_v
  desc: 'Rigid body on R2, controlled in velocity.'
  code: 
  - vehicles.library.dynamics.EuclideanVel
  - ndim: 2
    max_velocity: [*MAX_LINEAR_VEL, *MAX_LINEAR_VEL]

- id:   d_R3_rb_v
  desc: 'Rigid body on R2, controlled in velocity.'
  code: 
  - vehicles.library.dynamics.EuclideanVel
  - ndim: 3 
    max_velocity: [*MAX_LINEAR_VEL, *MAX_LINEAR_VEL, *MAX_LINEAR_VEL]

- id:   d_R1_rb_f
  desc: 'Rigid body on R1, controlled in force.'
  code: 
  - vehicles.library.dynamics.EuclideanForce
  - ndim: 1 
    max_force: [*MF] 
    mass: *MASS
    damping: *DAMPING

- id: d_R2_rb_f
  desc: 'Rigid body on R2, controlled in force.'
  code: [vehicles.library.dynamics.EuclideanForce, {ndim: 2, max_force: [*MF,*MF], mass: *MASS,  damping: *DAMPING} ]

- id  : d_R3_rb_f
  desc: 'Rigid body on R2, controlled in force.'
  code: [vehicles.library.dynamics.EuclideanForce, {ndim: 3, max_force: [*MF,*MF,*MF], mass: *MASS,  damping: *DAMPING} ]

- id:   d_SO3_rb_f
  desc: 'Rigid body in SO3, controlled in force.'
  code: [vehicles.library.dynamics.SO3Force, { max_force: [*MF,*MF,*MF], mass: *MASS,  damping: *DAMPING } ]

- id  : d_SO3_rb_v
  desc: 'Rigid body on SO3, controlled in velocity.'
  code: [vehicles.library.dynamics.SO3Vel, { max_angular_velocity: [*MA,*MA,*MA]} ]

# Now things on S1
- id: d_S1_rb_v
  desc: 'Particle on S1 controlled in velocity.'
  code: [vehicles.library.dynamics.CircleVel, {max_velocity: *MAX_LINEAR_VEL} ]
  
- id: d_S1_rb_f
  desc: 'Particle on S1 controlled in force.'
  code: [vehicles.library.dynamics.CircleForce, {max_force: *MF, mass: *MASS,  damping: *DAMPING} ]

# Now things on SE2
- id: d_SE2_rb_v
  desc: 'Planar robot on SE2 controlled in velocity'
  code: [vehicles.library.dynamics.SE2Dynamics, 
            {max_linear_velocity: [*MAX_LINEAR_VEL,*MAX_LINEAR_VEL], 
             max_angular_velocity: *MA} ]

- id: d_SE2_rb_f
  desc: 'Planar robot on SE2 controlled in force'
  code: [vehicles.library.dynamics.SE2Force, 
            { max_force: [*MF,*MF,*MF], mass: *MASS,  damping: *DAMPING} ]

# - id: d_SE2_fwd_f
#   desc: 'Planar vehicle with fixed forward velocity, controlled in angular velocity.'
#   code: [vehicles.library.dynamics.SE2ForwardDyn, 
#             {max_linear_velocity: *MF, mass: *MASS,  damping: *DAMPING,
#              linear_velocity: *MAX_LINEAR_VEL}]
             
- id: d_SE2_fwd_v
  desc: 'Planar vehicle with fixed forward velocity, controlled in angular velocity.'
  code: 
  - vehicles.library.dynamics.SE2Forward
  - max_angular_velocity: 0.2 
    linear_velocity: *MAX_LINEAR_VEL


# Now things on SE2
- id: d_SE2_dd_v
  desc: 'Differential drive robot on SE2'
  code: 
  - vehicles.library.dynamics.DifferentialDrive
  - max_linear_velocity: 1.0
    max_angular_velocity: 0.2

- id: d_SE2_dd_v2
  desc: 'Differential drive robot on SE2 (faster angular velocity)'
  code: 
  - vehicles.library.dynamics.DifferentialDrive
  - max_linear_velocity: 1.0
    max_angular_velocity: 1.0

# TODO: d_SE2_rb_f
# TODO: d_SE3_rb_v
# TODO: d_SE3_rb_f

- id: d_SE2_car_v
  desc: 'The simple car'
  code: 
      - vehicles.library.dynamics.SimpleCar
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
        axis_dist: *AXIS_DIST

- id: d_SE2_reeds_sheep
  desc: 'Reeds-Sheep car'
  code: 
      - vehicles.library.dynamics.ReedsSheepCar
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
        axis_dist: *AXIS_DIST
        
- id: d_SE2_dubins
  desc: 'Dubins car'
  code: 
      - vehicles.library.dynamics.DubinsCar
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
        axis_dist: *AXIS_DIST
        

- id: d_SE2_car_v_w
  desc: 'The simple car (with wheels joints)'
  code: 
      - vehicles.library.dynamics.CarWithWheels
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
        axis_dist: *AXIS_DIST

- id: d_SE2_reeds_sheep_w
  desc: 'Reeds-Sheep car (with wheels)'
  code: 
      - vehicles.library.dynamics.ReedsSheepCarWithWheels
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
        axis_dist: *AXIS_DIST
                
                
- id: d_SE2_dubins_w
  desc: 'Dubins car (with wheels)'
  code: 
      - vehicles.library.dynamics.DubinsCarWithWheels
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
        axis_dist: *AXIS_DIST

         
- id: d_fixed
  desc: 'A robot that is out of battery.'
  code: 
  - vehicles.library.dynamics.SE2Dynamics
  - max_linear_velocity: [0, 0]
    max_angular_velocity: 0

# 
# 
# d_SE2_RR_v
# d_SE2_RR_f
# d_SE2_RRR_v
# d_SE2_RRR_f
