# Define constants
# OK, now we start
- MAX_LINEAR_VEL: &MAX_LINEAR_VEL 1  # max linear velocity
  MA: &MA 1  # max angular velocity
  MF: &MF 2  # max force
  MASS: &MASS 1  # robot mass  
  CAR_LENGTH: &CAR_LENGTH 0.5
  DAMPING: &DAMPING 1
  MAX_STEERING_ANGLE: &MAX_STEERING_ANGLE 0.52359877 # 30deg
  id:   d_R1_rb_v
  desc: 'Rigid body on R1, controlled in velocity.'
  code: [vehicles_dynamics.EuclideanVel, {ndim: 1, max_velocity: [*MAX_LINEAR_VEL]} ]

- id:   d_R2_rb_v
  desc: 'Rigid body on R2, controlled in velocity.'
  code: [vehicles_dynamics.EuclideanVel, {ndim: 2, max_velocity: [*MAX_LINEAR_VEL, *MAX_LINEAR_VEL]}]

- id:   d_R3_rb_v
  desc: 'Rigid body on R2, controlled in velocity.'
  code: [vehicles_dynamics.EuclideanVel, {ndim: 3, max_velocity: [*MAX_LINEAR_VEL, *MAX_LINEAR_VEL, *MAX_LINEAR_VEL]} ]

- id:   d_R1_rb_f
  desc: 'Rigid body on R1, controlled in force.'
  code: [vehicles_dynamics.EuclideanForce, {ndim: 1, max_force: [*MF], mass: *MASS,  damping: *DAMPING} ]

- id: d_R2_rb_f
  desc: 'Rigid body on R2, controlled in force.'
  code: [vehicles_dynamics.EuclideanForce, {ndim: 2, max_force: [*MF,*MF], mass: *MASS,  damping: *DAMPING} ]

- id  : d_R3_rb_f
  desc: 'Rigid body on R2, controlled in force.'
  code: [vehicles_dynamics.EuclideanForce, {ndim: 3, max_force: [*MF,*MF,*MF], mass: *MASS,  damping: *DAMPING} ]

- id:   d_SO3_rb_f
  desc: 'Rigid body in SO3, controlled in force.'
  code: [vehicles_dynamics.SO3Force, { max_force: [*MF,*MF,*MF], mass: *MASS,  damping: *DAMPING } ]

- id  : d_SO3_rb_v
  desc: 'Rigid body on SO3, controlled in velocity.'
  code: [vehicles_dynamics.SO3Vel, { max_angular_velocity: [*MA,*MA,*MA]} ]

# Now things on S1
- id: d_S1_rb_v
  desc: 'Particle on S1 controlled in velocity.'
  code: [vehicles_dynamics.CircleVel, {max_velocity: *MAX_LINEAR_VEL} ]
  
- id: d_S1_rb_f
  desc: 'Particle on S1 controlled in force.'
  code: [vehicles_dynamics.CircleForce, {max_force: *MF, mass: *MASS,  damping: *DAMPING} ]

# Now things on SE2
- id: d_SE2_rb_v
  desc: 'Planar robot on SE2'
  code: [vehicles_dynamics.SE2Dynamics, 
            {max_linear_velocity: [*MAX_LINEAR_VEL,*MAX_LINEAR_VEL], 
             max_angular_velocity: *MA} ]

# Now things on SE2
- id: d_SE2_dd_v
  desc: 'Differentail drive robot on SE2'
  code: [vehicles_dynamics.DifferentialDrive, 
            {max_linear_velocity: 1, 
             max_angular_velocity: 0.2} ]

- id: d_SE2_dd_v2
  desc: 'Differentail drive robot on SE2 (faster angular velocity)'
  code: [vehicles_dynamics.DifferentialDrive, 
            {max_linear_velocity: 1, 
             max_angular_velocity: 1} ]

# TODO: d_SE2_rb_f
# TODO: d_SE3_rb_v
# TODO: d_SE3_rb_f
- id: d_SE2_car_v
  desc: 'The simple car'
  code: 
      - vehicles_dynamics.SimpleCar
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
- id: d_SE2_reeds_sheep
  desc: 'Reeds-Sheep car'
  code: 
      - vehicles_dynamics.ReedsSheepCar
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
- id: d_SE2_dubins
  desc: 'Dubins car'
  code: 
      - vehicles_dynamics.DubinsCar
      - max_linear_velocity: *MAX_LINEAR_VEL
        max_steering_angle: *MAX_STEERING_ANGLE
        L: *CAR_LENGTH
# Now things on SE2
- id: d_fixed
  desc: 'A robot that is out of battery.'
  code: [vehicles_dynamics.SE2Dynamics, 
            {max_linear_velocity: [0,0], 
             max_angular_velocity: 0} ]

# 
# 
# d_SE2_RR_v
# d_SE2_RR_f
# d_SE2_RRR_v
# d_SE2_RRR_f
