- id: box10
  desc: A 10m by 10m empty box.
  code: 
      - vehicles.worlds.Box
      - width: 10
        length: 10

- id: empty
  desc: The void.
  code: 
      - vehicles.worlds.Empty
      - bounds: [[-10,10],[-10,10],[-10,10]]
      
- id: test_dynamic
  desc: A test of a world with moving objects.
  code: 
      - vehicles.worlds.DynamicTest
      - width: 10
        length: 10
        
- id: stochastic_box_10
  desc: A box with stochastic content
  code: 
      - vehicles.worlds.StochasticBox
      - width: 10
        length: 10

- id: SBox2_10a
  desc: A box with stochastic content
  code: 
      - vehicles.worlds.StochasticBox2
      - width: 10
        length: 10
        num_sources: 10
        source_width: 3

- id: SBox3_10scale1
  desc: "A box with stochastic content, smoothed textures, scale=1m"
  code: 
      - vehicles.worlds.StochasticBox3
      - width: 10
        length: 10
        scale: 1
        sigma: 0.5

- id: SBox3_10scale05
  desc: "A box with stochastic content, smoothed textures, scale=0.5m"
  code: 
      - vehicles.worlds.StochasticBox3
      - width: 10
        length: 10
        scale: 0.5
        sigma: 0.25
