- id: box10
  desc: A 10m by 10m empty box.
  code: 
      - vehicles.worlds.Box
      - width: 10
        length: 10

- id: empty
  desc: The void.
  code: 
      - vehicles.worlds.Empty
      - bounds: [[-10,10],[-10,10],[-10,10]]
      
      
- id: test_dynamic
  desc: A test of a world with moving objects.
  code: 
      - vehicles.worlds.DynamicTest
      - width: 10
        length: 10