- id: d_SE2_car_v-cam360
  desc: A simple car with an omnidirectional camera.
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: cam_f360_n180
        pose: [0,0,0]
  radius: 0.5

- id: d_SE2_rb_v-rf360
  desc: An omnidirectional robot with a 360deg range finder.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: rf360
        pose: [0,0,0]
  radius: 0.5


- id: d_SE2_rb_v-rf180
  desc: An omnidirectional robot with a 180deg range finder.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: rf180
        pose: [0,0,0]
  radius: 0.5

- id: d_SE2_rb_v-cam180
  desc: An omnidirectional robot with a 180deg camera.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: cam_f180_n180
        pose: [0,0,0]
  radius: 0.5

- id: d_SE2_rb_v-cam180-stereo
  desc: An omnidirectional robot with two 180deg camera.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: cam_f180_n90
        pose: [0,0.5,0]
      - id_sensor: cam_f180_n90
        pose: [0,-0.5,0]
  radius: 0.5



- id: d_SE2_rb_v-random_5
  desc: An omnidirectional robot with a 5-sensels random sensor.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: random_5
        pose: [0,0,0]
  radius: 0.5
  
- id: landroid-hokuyo
  desc: "Model for the landroid; only Hokuyo."
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: rf_f270_n180
        pose: [0,0,0]
  radius: 0.2
  
- id: landroid-hokuyo-4cam
  desc: "Model for the landroid; Hokuyo + cams"
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: rf_f270_n180
        pose: [0.1,0,0]
      - id_sensor: cam_f60_n45
        pose: [0,0,0]
      - id_sensor: cam_f60_n45
        pose: [0,0,+90]
      - id_sensor: cam_f60_n45
        pose: [0,0,-90]
      - id_sensor: cam_f60_n45
        pose: [0,0,180]
  radius: 0.2
  
- id: landroid-4cam
  desc: "Model for the landroid; only cam"
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: cam_f60_n45
        pose: [0,0,0]
      - id_sensor: cam_f60_n45
        pose: [0,0,+90]
      - id_sensor: cam_f60_n45
        pose: [0,0,-90]
      - id_sensor: cam_f60_n45
        pose: [0,0,180]
  radius: 0.2

- id: orb-1d
  desc: "An orb controlled in velocity"
  id_dynamics: d_S1_rb_v
  sensors:
      - id_sensor: cam_f60_n45
        pose: [0,0,0]
  radius: 0.2

  
- id: example_custom_vehicle
  desc: Specifies everything explicitly
  dynamics: 
      id: example_custom_dynamics
      desc: 'Particle on S1 controlled in force.'
      code: [vehicles_dynamics.CircleForce, {max_force: 1, mass: 1, damping: 2} ]
  sensors:
      - pose: [0,0,0]
        sensor:         
            id: my_cam
            desc: A camera with 180fov.
            code: 
              - vehicles.sensors.PhotoreceptorsUniform
              - num_sensels: 180
                fov_deg:     180
  radius: 0.5