- id: default_skin
  desc: "Default skin; a circular robot."
  code:
  - vehicles_cairo.skins.circular
  - {}

- id: circular
  desc: "A circular robot."
  code:
  - vehicles_cairo.skins.circular
  - {}
# 
# - id: ddrive
#   desc: "Round differential-drive."
#   code:
#   - vehicles_cairo.skins.ddrive
#   - {}

# Use braiteberg for all differential drive
- id: ddrive
  desc: "Braitenberg base + receptors."
  code:
    - vehicles_cairo.skins.brai
    - sensors: True
  

- id: omni
  desc: "Round omnidirectinal."
  code:
  - vehicles_cairo.skins.omni
  - {}
  
  
- id: car_with_wheels
  desc: "Car with moving wheels"
  code:
  - vehicles_cairo.skins.ComplexSkin
  - skins:
      - joint: 1
        skin: wheel
      - joint: 2
        skin: wheel
      - joint: 0
        skin: car

- id: car
  desc: "A simple car."
  code:
  - vehicles_cairo.skins.car
  - {}


- id: wheel
  desc: "Wheel skin"
  code:
  - vehicles_cairo.skins.wheel
  - {} # w=0.7, h=0.5):



- id: brai_base
  desc: "Braitenberg base."
  code:
  - vehicles_cairo.skins.brai
  - sensors: False

- id: brai_classic
  desc: "Braitenberg base + receptors."
  code:
  - vehicles_cairo.skins.brai
  - sensors: True

- id: Rangefinder
  desc: "Default skin for rangefinder"
  code:
  - vehicles_cairo.skins.sick
  - size: 0.45

- id: Photoreceptors
  desc: "Default skin for Photoreceptors"
  code:
  - vehicles_cairo.skins.eye
  - size: 0.20

- id: FieldSampler
  desc: "Default skin for FieldSampler (transparent)"
  code:
  - vehicles_cairo.skins.transparent
  - {}

- id: RandomSensor
  desc: "Default skin for RandomSensor (transparent)"
  code:
  - vehicles_cairo.skins.transparent
  - {}

- id: transparent
  desc: "Transparent skin (do not draw)"
  code:
  - vehicles_cairo.skins.transparent
  - {}


