- id: d_SE2_car_v-cam360
  desc: A simple car with an omnidirectional camera.
  id_dynamics: d_SE2_car_v
  sensors:
      - id_sensor: cam360
        pose: [0,0,0]
  radius: 0.5

- id: d_SE2_rb_v-rf360
  desc: An omnidirectional robot with a 360deg range finder.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: rf360
        pose: [0,0,0]
  radius: 0.5

- id: d_SE2_rb_v-random_5
  desc: An omnidirectional robot with a 5-sensels random sensor.
  id_dynamics: d_SE2_rb_v
  sensors:
      - id_sensor: random_5
        pose: [0,0,0]
  radius: 0.5
  
- id: example_custom_vehicle
  desc: Specifies everything explicitly
  dynamics: 
      id: example_custom_dynamics
      desc: 'Particle on S1 controlled in force.'
      code: [vehicles_dynamics.CircleForce, {max_force: 1, mass: 1} ]
  sensors:
      - pose: [0,0,0]
        sensor:         
            id: my_cam
            desc: A camera with 180fov.
            code: 
              - vehicles.sensors.PhotoreceptorsUniform
              - num_sensels: 180
                fov_deg:     180
  radius: 0.5