# This file describes the available sensors
- id: cam_f360_n180
  desc: An omnidirectional camera with 180 sensels.
  code: 
      - vehicles.library.sensors.PhotoreceptorsUniform
      - num_sensels: 180
        fov_deg:     360
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05          
      
- id: cam_f180_n180
  desc: "A camera with 180fov, 180sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsUniform
      - num_sensels: 180
        fov_deg:     180
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05
        
- id: cam_f180_n90
  desc: "A camera with 180fov, 90 sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsUniform
      - num_sensels: 90
        fov_deg:     180
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05

- id: cam_f90_n45
  desc: "A camera with 90deg fov, 45 sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsUniform
      - num_sensels: 45
        fov_deg:     90
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05

- id: cam_f60_n45
  desc: "A camera with 60deg fov, 45 sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsUniform
      - num_sensels: 45
        fov_deg:     60
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05

# Smoothed version: we use sigma = 2 * pixel interval
# for example: 
#  num_sensels: 180
#   fov_deg:     360
#  sigma = 2*fov_deg / num_sensels) = 4

- id: cam_f360_n180_s
  desc: An omnidirectional camera with 180 sensels (smooth).
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 4
        upsample: 15
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05

# This is our default camera
- id: cam360
  desc: An omnidirectional camera with 180 sensels (smooth).
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 4
        upsample: 15
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05




- id: cam_f180_n180_s
  desc: "A camera with 180fov, 180sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 2
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05
        
- id: cam180
  desc: "A camera with 180fov, 90 sensels, smooth (default)"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 90
        fov_deg:     180
        spatial_sigma_deg: 4
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05
        
        
- id: cam_f180_n90_s
  desc: "A camera with 180fov, 90 sensels, smooth (default)"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 90
        fov_deg:     180
        spatial_sigma_deg: 4
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05



- id: cam_f90_n45_s
  desc: "A camera with 90deg fov, 45 sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 45
        fov_deg:     90
        spatial_sigma_deg: 4
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05

- id: cam_f60_n45_s
  desc: "A camera with 60deg fov, 45 sensels."
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 45
        fov_deg:     60
        spatial_sigma_deg: 2.7
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.05




- id: rf360
  desc: An omnidirectional range-finder.
  code: 
      - vehicles.library.sensors.RangefinderUniform
      - num_sensels: 180
        fov_deg:     360
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.01
        
- id: rf180
  desc: A range finder with 180fov.
  code: 
      - vehicles.library.sensors.RangefinderUniform
      - num_sensels: 180
        fov_deg:     180
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.01

- id: rf_f270_n180
  desc: "A range finder with 270deg fov, 180 sensels."
  code: 
      - vehicles.library.sensors.RangefinderUniform
      - num_sensels: 180
        fov_deg:     270
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.01

- id: random_5
  desc: A random sensor with 5 sensels.
  code: 
      - vehicles.library.sensors.RandomSensor
      - num_sensels: 5
        
- id: fs_05_12x12
  desc: "A field sampler with a 12x12 display."
  code: 
      - vehicles.library.sensors.FieldSamplerUniform
      - shape: [12,12]
        sides: [0.22,0.22]
        normalize: False
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.015

- id: fs_05_rand144
  desc: "A field sampler with a 12x12 display."
  code: 
      - vehicles.library.sensors.FieldSamplerRandCircle
      - n: 144
        radius: 0.25
        normalize: False
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: 0.015

  
