# This file describes the available sensors
- id: cam_f360_n180
  desc: An omnidirectional camera with 180 sensels.
  code: 
      - vehicles.sensors.PhotoreceptorsUniform
      - num_sensels: 180
        fov_deg:     360
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.05
        
- id: cam_f180_n180
  desc: "A camera with 180fov, 180sensels."
  code: 
      - vehicles.sensors.PhotoreceptorsUniform
      - num_sensels: 180
        fov_deg:     180
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.05
        
- id: cam_f180_n90
  desc: "A camera with 180fov, 90 sensels."
  code: 
      - vehicles.sensors.PhotoreceptorsUniform
      - num_sensels: 90
        fov_deg:     180
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.05

- id: cam_f90_n45
  desc: "A camera with 90deg fov, 45 sensels."
  code: 
      - vehicles.sensors.PhotoreceptorsUniform
      - num_sensels: 45
        fov_deg:     90
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.05

- id: cam_f60_n45
  desc: "A camera with 60deg fov, 45 sensels."
  code: 
      - vehicles.sensors.PhotoreceptorsUniform
      - num_sensels: 45
        fov_deg:     60
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.05
        
- id: rf360
  desc: An omnidirectional range-finder.
  code: 
      - vehicles.sensors.RangefinderUniform
      - num_sensels: 180
        fov_deg:     360
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.01
        
- id: rf180
  desc: A range finder with 180fov.
  code: 
      - vehicles.sensors.RangefinderUniform
      - num_sensels: 180
        fov_deg:     180
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.01

- id: rf_f270_n180
  desc: "A range finder with 270deg fov, 180 sensels."
  code: 
      - vehicles.sensors.RangefinderUniform
      - num_sensels: 180
        fov_deg:     270
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.01

- id: random_5
  desc: A random sensor with 5 sensels.
  code: 
      - vehicles.sensors.RandomSensor
      - num_sensels: 5
        
- id: fs_05_12x12
  desc: "A field sampler with a 12x12 display."
  code: 
      - vehicles.sensors.FieldSamplerUniform
      - shape: [12,12]
        sides: [0.22,0.22]
        normalize: True
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.0

- id: fs_05_rand144
  desc: "A field sampler with a 12x12 display."
  code: 
      - vehicles.sensors.FieldSamplerRandCircle
      - n: 144
        radius: 0.25
        normalize: True
        noise: 
            - vehicles.sensors.AdditiveGaussian
            - std_dev: 0.0

  
